### ISSUE TITLE
Email notifications use titles from different sources

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#161]
Notifications seem to use titles from different sources, some of which are not translated.

Example from: https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2597

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/4d1868d4-8f48-4654-835d-7d9ec6250b63)

**Comment by microstudi** [comment]
This looks like the underlying bug is more profound. The original proposal was writen in english and french (official) but the amendment was writen in english only, then it has been automatically translated to french and the original french has been lost.

A part of that, looks like the amendment has been accepted while looking the page in french language and the original language has been swapped (the text in english has gone to the french language), then the original french has been lost. This is clearly a bug and we can solved, but the interaction between automatically translated text and original text is very tricky

**Comment by paarals** [comment]
closed via #153
