### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#34]
**Acceptance criteria**
-[ ] No changes
![LCC Website Planning - Frame 10](https://user-images.githubusercontent.com/40388743/183704655-25e4bb59-a388-4488-8213-92a281cdd61d.jpg)

**Comment by BigSnicker** [comment]
@paarals A possible issue here. We may have a very large number of meetings from many competing campaigns. The order that they are presented in thus becomes important. We may have to look at what happens when we schedule a lot of meetings on one day, and we may have to consider listing them in random order, if possible.

**Comment by BigSnicker** [comment]
If we cannot randomize it, then we may just have to go without the calendar. To be discussed.

**Comment by BigSnicker** [comment]
I think this is done!

**Comment by BigSnicker** [comment]
Gaaha. I just realized. Can we take "debates' off? That could create the possibility for abuse.

**Comment by BigSnicker** [comment]
Forget that. Have a new idea. Consider this closed.
