### ISSUE TITLE
New sign up page

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#60]
Inspiration: https://participa.somenergia.coop/users/sign_in?locale=ca

URL: https://staging.deploy.green.ca/users/sign_in

- [x] Enable sign in with CiviCRM. Text must be: "Sign in with GPC account" / "S'identifier au compte PVC"
- [x] Hide username/password of decidim sign in and but a button as Sign in with Decidim. Text must be "Sign in for non GPC members and administrators"

**Comment by BigSnicker** [comment]
I just realized that having an option for non-GPC members will create a problem for us, because staff will have to answer a lot of questions about the process for getting a non-member account, something that we expect to be exceedingly rare.

Hopefully @Laurence-Montgomery will provide input, but I'd like to change the second task...

- [ ] Sign-in screen similar to [somenergia](https://participa.somenergia.coop/users/sign_in?locale=ca), with one button going to CiviCRM ("Sign in with GPC account" / "S'identifier au compte PVC") and another button hiding the decidim log-in credentials, saying "Sign-in with special accounts" / "S'identifier avec des comptes spéciaux"

**Comment by Laurence-Montgomery** [comment]
Lets stick with the original - "Sign in with GPC account" and "Admin Sign in"
The 'special account' will cause all sorts of pointless intrigue.

**Comment by BigSnicker** [comment]
Based on feedback from @Laurence-Montgomery 

- [ ] Sign-in screen similar to [somenergia](https://participa.somenergia.coop/users/sign_in?locale=ca), with one button going to CiviCRM ("Sign in with GPC account" / "S'identifier au compte PVC") and another button hiding the decidim log-in credentials, saying "Admin sign-in" / "Connexion admin"

**Comment by microstudi** [comment]
wil be fixed by #66
